name: Stories check

on:
  pull_request:
    branches:
      - main

jobs:
  checkScreenshots:
    name: Stories check

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: PNPM install
        run: pnpm i --frozen-lockfile

      - name: Run stories-check
        id: storiesCheck
        continue-on-error: true
        run: pnpm stories-check

      - name: Commit story changes
        id: csc
        if: steps.storiesCheck.outcome == 'failure'
        uses: EndBug/add-and-commit@v9
        with:
          add: ".stories-approved"
          message: "[skip ci] [stories-check] Automated story changes"
          new_branch: ${{ github.head_ref }}
          default_author: github_actions
